ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH06_KDY
IDENTIFIED BY "KH1234";

ALTER USER KH06_KDY
DEFAULT TABLESPACE "USERS"
QUOTA 200M ON "USERS";


GRANT CONNECT, RESOURCE,CREATE VIEW TO KH06_KDY;