SELECT DEPARTMENT_NAME 학과명 ,CATEGORY 계열 
FROM TB_DEPARTMENT ;

SELECT (DEPARTMENT_NAME ||'의 정원은 '||CAPACITY|| '명 입니다') AS "학과별 정원"
FROM TB_DEPARTMENT ;

SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO ='001' AND ABSENCE_YN ='Y' AND SUBSTR(STUDENT_SSN,8,1)=2 ;

SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO in('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC


SELECT DEPARTMENT_NAME ,CATEGORY 
FROM TB_DEPARTMENT 
WHERE CAPACITY BETWEEN 20 and 30

SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR 
